spring:
  application:
    name: bundleboard
  r2dbc:
    url: r2dbc:postgresql://postgres:${POSTGRES_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  graphql:
    graphiql:
      enabled: true
      show-exceptions: true
    schema:
      inspection:
        enabled: true
      printer:
        enabled: true
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
logging:
  level:
    org.springframework.r2dbc: DEBUG

app:
  jwt:
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 2592000000
