spring:
  profiles:
    active: dev
  application:
    name: bundleboard
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT:6543}/${POSTGRES_DB:postgres}?options=-c%20search_path%3D${POSTGRES_SCHEMA:public}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool:
      enabled: true
      initial-size: ${DB_POOL_SIZE}
      max-size: ${DB_MAX_POOL_SIZE}

  graphql:
    graphiql:
      enabled: true
      show-exceptions: true
    schema:
      inspection:
        enabled: true
      printer:
        enabled: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG

server:
  port: ${SERVER_PORT}

app:
  auth:
    social-password-secret: ${SOCIAL_AUTH_PASSWORD_SECRET}

  cors:
        allowed-origins: ${ALLOWED_ORIGINS}
        allowed-methods: ${ALLOWED_METHODS}
        allowed-headers: ${ALLOWED_HEADERS}
        allowed-credentials: ${ALLOWED_CREDENTIALS}
        exposed-headers: ${EXPOSED_HEADERS}
        max-age: ${MAX_AGE}

  jwt:
    access-token-expiration-ms: ${JWT_ACCESS_EXPIRY}
    refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRY}
    secret: ${JWT_SECRET}

  mail:
    from: ${spring.mail.username}
    templates:
      verification-email: mail/verify-email
      reset-password: mail/reset-password

    subjects:
      verification-email: Verify Email
      reset-password: Reset Password

    paths:
      verification-email: /mail/verify
      reset-password: /password/reset-password


  email-verification:
    ttl-ms: ${EMAIL_VERIFICATION_TTL_MS}
    verify-email-url: ${VERIFY_EMAIL_URL}
    hash-algorithm: ${EMAIL_HASH_ALGORITHM}
    hex-format: ${EMAIL_HEX_FORMAT}
    hash-length: ${EMAIL_HASH_LENGTH}
    byte-length: ${EMAIL_BYTE_LENGTH}
    max-attempts: ${MAX_ATTEMPTS}
    block-duration-seconds: ${BLOCK_DURATION_SECONDS}

  password-verification:
    max-attempts: ${MAX_ATTEMPTS}
    block-duration-seconds: ${BLOCK_DURATION_SECONDS}