spring:
  profiles:
    active: staging
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_DB}?options=-c%20search_path%3D${POSTGRES_SCHEMA}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

  logging:
    level:
      root: INFO
      com.source.bundleboard: INFO
      org.springframework.security: INFO
      org.springframework.graphql: INFO
      io.r2dbc.postgresql: WARN

app:
  frontend-url: ${FRONTEND_URL:https://staging.bundleboard.com}

  cors:
    allowed-origins: ${ALLOWED_ORIGINS:https://staging.bundleboard.com}

  jwt:
    secret: ${JWT_SECRET}

  mail:
    api-key: ${MAIL_API_KEY}
    from: ${MAIL_FROM:staging.bundleboard@gmail.com}

  email-verification:
    verify-email-url: ${VERIFY_EMAIL_URL:https://staging.bundleboard.com}

  s3:
    endpoint: ${S3_ENDPOINT}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    previews-public-url-prefix: ${S3_PREVIEWS_URL_PREFIX}

  graphql:
    graphiql:
      enabled: ${GRAPHIQL_ENABLED:false}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  public-key: ${STRIPE_PUBLIC_KEY}
  webhook-secret: ${WEBHOOK_SECRET_KEY}
  payment-success-url: ${PAYMENT_SUCCESS_URL:https://staging.bundleboard.com/payment/success}
  payment-cancel-url: ${PAYMENT_CANCEL_URL:https://staging.bundleboard.com/payment/cancel}