spring:
  profiles:
    active: dev
  application:
    name: bundleboard
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_URL:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}?options=-c%20search_path%3D${POSTGRES_SCHEMA:public}
    username: ${POSTGRES_USER:bundleboard_user}
    password: ${POSTGRES_PASSWORD:bundleboard_password}
    pool:
      enabled: true
      initial-size: ${DB_POOL_SIZE:2}
      max-size: ${DB_MAX_POOL_SIZE:10}

  data:
    redis:
      repositories:
        enabled: false

  graphql:
    graphiql:
      enabled: ${GRAPHIQL_ENABLED:true}
    schema:
      inspection:
        enabled: true
      printer:
        enabled: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}
    media-queue: bundleboard.media.queue
    email-queue: bundleboard.email.queue
    webhook-queue: bundleboard.webhook.queue

logging:
  level:
    root: TRACE
    org.springframework.security: ${LOG_LEVEL_SECURITY:TRACE}
    org.springframework.security.authorization: ${LOG_LEVEL_SECURITY:TRACE}
    org.springframework.security.web.server: ${LOG_LEVEL_WEB_SECURITY:TRACE}
    org.springframework.graphql: ${LOG_LEVEL_GRAPHQL:TRACE}
    org.springframework.r2dbc: ${LOG_LEVEL_R2DBC:TRACE}
    io.r2dbc.postgresql: ${LOG_LEVEL_POSTGRES:TRACE}

server:
  port: ${SERVER_PORT:8080}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  auth:
    social-password-secret: ${SOCIAL_AUTH_PASSWORD_SECRET:default-secret-change-me}

  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
    allowed-methods: ${ALLOWED_METHODS:GET,POST,PUT,DELETE}
    allowed-headers: ${ALLOWED_HEADERS:*}
    allowed-credentials: ${ALLOWED_CREDENTIALS:true}
    exposed-headers: ${EXPOSED_HEADERS:Authorization}
    max-age: ${MAX_AGE:3600}

  jwt:
    access-token-expiration-ms: ${JWT_ACCESS_EXPIRY:3600000}
    refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRY:86400000}
    secret: ${JWT_SECRET:very-long-secret-key-that-is-at-least-512-bits-long-for-security-purposes}

  mail:
    api-key: ${MAIL_API_KEY:test_key}
    from: ${MAIL_FROM:bundleboard.app@gmail.com}
    from-name: "BundleBoard"

    templates:
      verification-email: mail/verify-email
      reset-password: mail/reset-password
      purchase-receipt: mail/purchase-receipt

    subjects:
      verification-email: Verify Email
      reset-password: Reset Password
      purchase-receipt: Purchase Receipt

    paths:
      verification-email: /mail/verify
      reset-password: /password/reset-password
      purchase-receipt: /mail/purchase-receipt

  email-verification:
    ttl-ms: ${EMAIL_VERIFICATION_TTL_MS:3600000}
    verify-email-url: ${VERIFY_EMAIL_URL:https://www.bundle-board.com}
    hash-algorithm: ${EMAIL_HASH_ALGORITHM:SHA-256}
    hex-format: ${EMAIL_HEX_FORMAT:true}
    hash-length: ${EMAIL_HASH_LENGTH:64}
    byte-length: ${EMAIL_BYTE_LENGTH:32}
    max-attempts: ${MAX_ATTEMPTS:3}
    block-duration-seconds: ${BLOCK_DURATION_SECONDS:300}

  password-verification:
    max-attempts: ${MAX_ATTEMPTS:3}
    block-duration-seconds: ${BLOCK_DURATION_SECONDS:300}

  s3:
    endpoint: ${S3_ENDPOINT:https://lemevepzkbfxkunmrgor.storage.supabase.co/storage/v1/s3}
    access-key: ${S3_ACCESS_KEY:5e36e380e1f774193a77ca1f750df8e4}
    secret-key: ${S3_SECRET_KEY:6ed04948146fd121d932bc4e4331c708c5b896856498a5e78f6393c195c2b02c}
    previews-bucket: ${S3_PREVIEWS_BUCKET:previews}
    previews-public-url-prefix: ${S3_PREVIEWS_URL_PREFIX:https://lemevepzkbfxkunmrgor.supabase.co/storage/v1/object/public/previews/}
    vault-bucket: ${S3_VAULT_BUCKET:vault}
    region: ${S3_REGION:us-east-1}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  public-key: ${STRIPE_PUBLIC_KEY}
  webhook-secret: ${WEBHOOK_SECRET_KEY}
  payment-success-url: ${PAYMENT_SUCCESS_URL}
  payment-cancel-url: ${PAYMENT_CANCEL_URL}